import { IDice } from '@krisnorman/rpg-utils';
import { IFooModel } from './FantasyTreasureGenerator.js';
import { ITableRow, MyTable } from './MyTable.js';

export class Spell implements IFooModel {
  constructor(private row: ITableRow) {        
      this.Title = row.Value;
    }
  
    readonly Title: string = '';
    readonly Items: string[] = [];
    readonly HasItems: boolean = false;

}

export class SpellRepository {
  private readonly spellsTable = new MyTable(SpellsData, "Spells", "1d338");

  constructor(private dice: IDice){}

  getRandom(count: number = 1): Spell[] {
    if (count < 1) count = 1;
    let spells: Spell[] = [];

    for (let index = 0; index < count; index++) {
        const roll = this.dice.roll(this.spellsTable.DieExpression);
        const row = this.spellsTable.find(roll.total);
        const spell = new Spell(row.Row);
        spells.push(spell);
    }

    return spells;
  }
}

export const SpellsData: ITableRow[] = [
  { Roll: 1, Value: 'Bless' },
  { Roll: 2, Value: 'Command' },
  { Roll: 3, Value: 'Create Water' },
  { Roll: 4, Value: 'Cure Light Wounds' },
  { Roll: 5, Value: 'Detect Magic' },
  { Roll: 6, Value: 'Light' },
  { Roll: 7, Value: 'Purify Food & Drink' },
  { Roll: 8, Value: 'Remove Fear' },
  { Roll: 9, Value: 'Resist Cold' },
  { Roll: 10, Value: 'Sanctuary' },
  { Roll: 11, Value: 'Augury' },
  { Roll: 12, Value: 'Chant' },
  { Roll: 13, Value: 'Detect Charm' },
  { Roll: 14, Value: 'Find Traps' },
  { Roll: 15, Value: 'Hold Person' },
  { Roll: 16, Value: 'Resist Fire' },
  { Roll: 17, Value: "Silence 15' Radius" },
  { Roll: 18, Value: 'Slow Poison' },
  { Roll: 19, Value: 'Snake Charm' },
  { Roll: 20, Value: 'Speak with Animals' },
  { Roll: 21, Value: 'Spiritual Hammer' },
  { Roll: 22, Value: 'Animate Dead' },
  { Roll: 23, Value: 'Continual Light' },
  { Roll: 24, Value: 'Create Food & Water' },
  { Roll: 25, Value: 'Cure Blindness' },
  { Roll: 26, Value: 'Cure Disease' },
  { Roll: 27, Value: 'Dispel Magic' },
  { Roll: 28, Value: 'Feign Death' },
  { Roll: 29, Value: 'Glyph of Warding' },
  { Roll: 30, Value: 'Locate Object' },
  { Roll: 31, Value: 'Prayer' },
  { Roll: 32, Value: 'Remove Curse' },
  { Roll: 33, Value: 'Speak with Dead' },
  { Roll: 34, Value: 'Cure Serious Wounds' },
  { Roll: 35, Value: 'Detect Lie' },
  { Roll: 36, Value: 'Divination' },
  { Roll: 37, Value: 'Exorcise' },
  { Roll: 38, Value: 'Lower Water' },
  { Roll: 39, Value: 'Neutralize Poison' },
  { Roll: 40, Value: 'Speak with Plants' },
  { Roll: 41, Value: 'Sticks to Snakes' },
  { Roll: 42, Value: 'Tongues' },
  { Roll: 43, Value: 'Atonement' },
  { Roll: 44, Value: 'Commune' },
  { Roll: 45, Value: 'Cure Critical Wounds' },
  { Roll: 46, Value: 'Flame Strike' },
  { Roll: 47, Value: 'Insect Plague' },
  { Roll: 48, Value: 'Plane Shift' },
  { Roll: 49, Value: 'Quest' },
  { Roll: 50, Value: 'Raise Dead' },
  { Roll: 51, Value: 'Ture Seeing' },
  { Roll: 52, Value: 'Aerial Servant' },
  { Roll: 53, Value: 'Animate Object' },
  { Roll: 54, Value: 'Blade Barrier' },
  { Roll: 55, Value: 'Conjure Animals' },
  { Roll: 56, Value: 'Find the Path' },
  { Roll: 57, Value: 'Heal' },
  { Roll: 58, Value: 'Part Water' },
  { Roll: 59, Value: 'Speak with Monsters' },
  { Roll: 60, Value: 'Stone Tell' },
  { Roll: 61, Value: 'Word of Recall' },
  { Roll: 62, Value: 'Astral Spell' },
  { Roll: 63, Value: 'Control Weather' },
  { Roll: 64, Value: 'Earthquake' },
  { Roll: 65, Value: 'Gate' },
  { Roll: 66, Value: 'Holy Word' },
  { Roll: 67, Value: 'Unholy Word' },
  { Roll: 68, Value: 'Regenerate' },
  { Roll: 69, Value: 'Restoration' },
  { Roll: 70, Value: 'Resurrection' },
  { Roll: 71, Value: 'Symbol' },
  { Roll: 72, Value: 'Wind Walk' },
  { Roll: 73, Value: 'Animal Friendship' },
  { Roll: 74, Value: 'Detect Snares & Pits' },
  { Roll: 75, Value: 'Faerie Fire' },
  { Roll: 76, Value: 'Invisibility to Animals' },
  { Roll: 77, Value: 'Pass Without Trace' },
  { Roll: 78, Value: 'Predict Weather' },
  { Roll: 79, Value: 'Shillelagh' },
  { Roll: 80, Value: 'Barkskin' },
  { Roll: 81, Value: 'Charm Person or Mammal' },
  { Roll: 82, Value: 'Fire Trap' },
  { Roll: 83, Value: 'Heat Metal' },
  { Roll: 84, Value: 'Locate Plants' },
  { Roll: 85, Value: 'Obscurement' },
  { Roll: 86, Value: 'Produce Flame' },
  { Roll: 87, Value: 'Trip' },
  { Roll: 88, Value: 'Warp Wood' },
  { Roll: 89, Value: 'Call Lightning' },
  { Roll: 90, Value: 'Hold Animal' },
  { Roll: 91, Value: 'Plant Growth' },
  { Roll: 92, Value: 'Protection from Fire' },
  { Roll: 93, Value: 'Pyrotechnics' },
  { Roll: 94, Value: 'Snare' },
  { Roll: 95, Value: 'Stone Shape' },
  { Roll: 96, Value: 'Summon Insects' },
  { Roll: 97, Value: 'Tree' },
  { Roll: 98, Value: 'Water Breathing' },
  { Roll: 99, Value: 'Animal Summoning I' },
  { Roll: 100, Value: 'Call Woodland Beings' },
  { Roll: 101, Value: "Control Temperature 10' Radius" },
  { Roll: 102, Value: 'Hallucinatory Forest' },
  { Roll: 103, Value: 'Hold Plant' },
  { Roll: 104, Value: 'Plant Door' },
  { Roll: 105, Value: 'Produce Fire' },
  { Roll: 106, Value: 'Protection from Lightning' },
  { Roll: 107, Value: 'Repeal Insects' },
  { Roll: 108, Value: 'Animal Growth' },
  { Roll: 109, Value: 'Animal Summoning II' },
  { Roll: 110, Value: 'Anti-Plant Shell' },
  { Roll: 111, Value: 'Commune with Nature' },
  { Roll: 112, Value: 'Control Winds' },
  { Roll: 113, Value: 'Pass Plant' },
  { Roll: 114, Value: 'Transmute Rock to Mud' },
  { Roll: 115, Value: 'Wall of Fire' },
  { Roll: 116, Value: 'Animal Summoning III' },
  { Roll: 117, Value: 'Anti-Animal Shell' },
  { Roll: 118, Value: 'Conjure Fire Elemental' },
  { Roll: 119, Value: 'Feeblemind' },
  { Roll: 120, Value: 'Fire Seeds' },
  { Roll: 121, Value: 'Transport via Plants' },
  { Roll: 122, Value: 'Turn Wood' },
  { Roll: 123, Value: 'Wall of Thorns' },
  { Roll: 124, Value: 'Weather Summoning' },
  { Roll: 125, Value: 'Animate Rock' },
  { Roll: 126, Value: 'Chariot of Sustarre' },
  { Roll: 127, Value: 'Confusion' },
  { Roll: 128, Value: 'Conjure Earth Elemental' },
  { Roll: 129, Value: 'Control Weather' },
  { Roll: 130, Value: 'Creeping Doom' },
  { Roll: 131, Value: 'Finger of Death' },
  { Roll: 132, Value: 'Fire Storm' },
  { Roll: 133, Value: 'Reincarnate' },
  { Roll: 134, Value: 'Transmute Metal to Wood' },
  { Roll: 135, Value: 'Affect Normal Fires' },
  { Roll: 136, Value: 'Burning Hands' },
  { Roll: 137, Value: 'Charm Person or Mammal' },
  { Roll: 138, Value: 'Comprehend Languages' },
  { Roll: 139, Value: 'Dancing Lights' },
  { Roll: 140, Value: 'Enlarge' },
  { Roll: 141, Value: 'Erase' },
  { Roll: 142, Value: 'Feather Fall' },
  { Roll: 143, Value: 'Find Familiar' },
  { Roll: 144, Value: 'Friends' },
  { Roll: 145, Value: 'Hold Portal' },
  { Roll: 146, Value: 'Identify' },
  { Roll: 147, Value: 'Jump' },
  { Roll: 148, Value: 'Light' },
  { Roll: 149, Value: 'Magic Missile' },
  { Roll: 150, Value: 'Mending' },
  { Roll: 151, Value: 'Message' },
  { Roll: 152, Value: "Nystul's Magic Aura" },
  { Roll: 153, Value: 'Push' },
  { Roll: 154, Value: 'Read Magic' },
  { Roll: 155, Value: 'Shield' },
  { Roll: 156, Value: 'Shocking Grasp' },
  { Roll: 157, Value: 'Sleep' },
  { Roll: 158, Value: 'Spider Climb' },
  { Roll: 159, Value: "Tenser's Floating Disk" },
  { Roll: 160, Value: 'Unseen Servant' },
  { Roll: 161, Value: 'Ventriloquism' },
  { Roll: 162, Value: 'Write' },
  { Roll: 163, Value: 'Audible Glamer' },
  { Roll: 164, Value: 'Continual Light' },
  { Roll: 165, Value: "Darkness 15' Radius" },
  { Roll: 166, Value: 'Detect Invisibility' },
  { Roll: 167, Value: 'ESP' },
  { Roll: 168, Value: "Fool's Gold" },
  { Roll: 169, Value: 'Forget' },
  { Roll: 170, Value: 'Invisibility to Animals' },
  { Roll: 171, Value: 'Knock' },
  { Roll: 172, Value: "Leomund's Trap" },
  { Roll: 173, Value: 'Levitate' },
  { Roll: 174, Value: 'Magic Mouth' },
  { Roll: 175, Value: 'Mirror Image' },
  { Roll: 176, Value: 'Ray of Enfeblement' },
  { Roll: 177, Value: 'Rope Trick' },
  { Roll: 178, Value: 'Scare' },
  { Roll: 179, Value: 'Shatter' },
  { Roll: 180, Value: 'Stinking CLoud' },
  { Roll: 181, Value: 'Strength' },
  { Roll: 182, Value: 'Web' },
  { Roll: 183, Value: 'Wizard Lock' },
  { Roll: 184, Value: 'Blind' },
  { Roll: 185, Value: 'Clairaudiance' },
  { Roll: 186, Value: 'Clairvoyance' },
  { Roll: 187, Value: 'Explosive Runes' },
  { Roll: 188, Value: 'Fireball' },
  { Roll: 189, Value: 'Flame Arrow' },
  { Roll: 190, Value: 'Fly' },
  { Roll: 191, Value: 'Gust of Wind' },
  { Roll: 192, Value: 'Haste' },
  { Roll: 193, Value: 'Infravision' },
  { Roll: 194, Value: "Invisibility 10' Radius" },
  { Roll: 195, Value: "Leomund's Tiny Hut" },
  { Roll: 196, Value: 'Lightning Bolt' },
  { Roll: 197, Value: 'Monster Summoning I' },
  { Roll: 198, Value: 'Phantasmal Force' },
  { Roll: 199, Value: 'Protection from Normal Missiles' },
  { Roll: 200, Value: 'Slow' },
  { Roll: 201, Value: 'Suggestion' },
  { Roll: 202, Value: 'Tongues' },
  { Roll: 203, Value: 'Charm Monster' },
  { Roll: 204, Value: 'Dig' },
  { Roll: 205, Value: 'Dimension Door' },
  { Roll: 206, Value: 'Enchanted Weapon' },
  { Roll: 207, Value: 'Extension I' },
  { Roll: 208, Value: 'Fire CHarm' },
  { Roll: 209, Value: 'Fire Shield' },
  { Roll: 210, Value: 'Fire Trap' },
  { Roll: 211, Value: 'Fumble' },
  { Roll: 212, Value: 'Hallucinatory Terrain' },
  { Roll: 213, Value: 'Ice Storm' },
  { Roll: 214, Value: 'Massmorph' },
  { Roll: 215, Value: 'Minor Glove of Invulerability' },
  { Roll: 216, Value: 'Monster Summoning II' },
  { Roll: 217, Value: 'Polymorph Other' },
  { Roll: 218, Value: "Rary's Mnemonic Enhancer" },
  { Roll: 219, Value: 'Wall of Ice' },
  { Roll: 220, Value: 'Wizard Eye' },
  { Roll: 221, Value: 'Airy Water' },
  { Roll: 222, Value: "Bigby's IMterposing Hand" },
  { Roll: 223, Value: 'Cloudkill' },
  { Roll: 224, Value: 'Cone of Cold' },
  { Roll: 225, Value: 'Contact Other Plane' },
  { Roll: 226, Value: 'Distance Distortion' },
  { Roll: 227, Value: 'Extension II' },
  { Roll: 228, Value: "Leomund's Secret Chest" },
  { Roll: 229, Value: 'Magic Jar' },
  { Roll: 230, Value: 'Monster Summoning III' },
  { Roll: 231, Value: "Mordenkainen's Faithful Hound" },
  { Roll: 232, Value: 'Passwall' },
  { Roll: 233, Value: 'Telekinesis' },
  { Roll: 234, Value: 'Teleport' },
  { Roll: 235, Value: 'Wall of Force' },
  { Roll: 236, Value: 'Wall of Iron' },
  { Roll: 237, Value: 'Wall of Stone' },
  { Roll: 238, Value: 'Anti-Magic Shell' },
  { Roll: 239, Value: "Bigby's Forceful Hand" },
  { Roll: 240, Value: 'Death Spell' },
  { Roll: 241, Value: 'Disintegrate' },
  { Roll: 242, Value: 'Enchant An Item' },
  { Roll: 243, Value: 'Extension III' },
  { Roll: 244, Value: 'Gaeas' },
  { Roll: 245, Value: 'Glassee' },
  { Roll: 246, Value: 'Globe of Invulnerability' },
  { Roll: 247, Value: 'Guards and Wards' },
  { Roll: 248, Value: 'Invisible Stalker' },
  { Roll: 249, Value: 'Legend Lore' },
  { Roll: 250, Value: 'Monster Summoning IV' },
  { Roll: 251, Value: 'Move Earth' },
  { Roll: 252, Value: "Otiluke's Freezing Sphere" },
  { Roll: 253, Value: 'Project Image' },
  { Roll: 254, Value: 'Repulsion' },
  { Roll: 255, Value: 'Spiritwrack' },
  { Roll: 256, Value: 'Stone to Flesh' },
  { Roll: 257, Value: "Tenser's Transformation" },
  { Roll: 258, Value: "Bigby's Grasping Hand" },
  { Roll: 259, Value: 'Cacodemon' },
  { Roll: 260, Value: 'Delayed Blast Fireball' },
  { Roll: 261, Value: "Drawmij's Instant Summons" },
  { Roll: 262, Value: 'Duo-Dimension' },
  { Roll: 263, Value: 'Limited Wish' },
  { Roll: 264, Value: 'Monster Summoning V' },
  { Roll: 265, Value: "Mordenkainen's Sword" },
  { Roll: 266, Value: 'Phase Door' },
  { Roll: 267, Value: 'Power Word Stun' },
  { Roll: 268, Value: 'Reverse Gravity' },
  { Roll: 269, Value: 'Simulacrum' },
  { Roll: 270, Value: 'Vanish' },
  { Roll: 271, Value: 'Antipathy' },
  { Roll: 272, Value: 'Sympathy' },
  { Roll: 273, Value: "Bigby's Clenched Fist" },
  { Roll: 274, Value: 'Clone' },
  { Roll: 275, Value: 'Glasssteel' },
  { Roll: 276, Value: 'Incendiary Cloud' },
  { Roll: 277, Value: 'Mass Charm' },
  { Roll: 278, Value: 'Maze' },
  { Roll: 279, Value: 'Mind Blank' },
  { Roll: 280, Value: 'Monster Summoning VI' },
  { Roll: 281, Value: "Otto's Irresistible Dance" },
  { Roll: 282, Value: 'Permanency' },
  { Roll: 283, Value: 'Polymorph Any Object' },
  { Roll: 284, Value: 'Power Word Blind' },
  { Roll: 285, Value: "Serten's Spell Immunity" },
  { Roll: 286, Value: 'Symbol' },
  { Roll: 287, Value: 'Trap the Soul' },
  { Roll: 288, Value: 'Astral Spell' },
  { Roll: 289, Value: "Bigyby's Crushing Hand" },
  { Roll: 290, Value: 'Gate' },
  { Roll: 291, Value: 'Imprisonment' },
  { Roll: 292, Value: 'Meteor Swarm' },
  { Roll: 293, Value: 'Monster Summoning VII' },
  { Roll: 294, Value: 'Power Word Kill' },
  { Roll: 295, Value: 'Prismatic Sphere' },
  { Roll: 296, Value: 'Shape Change' },
  { Roll: 297, Value: 'Temporal Stasis' },
  { Roll: 298, Value: 'Time Stamp' },
  { Roll: 299, Value: 'Wish' },
  { Roll: 300, Value: 'Change Self' },
  { Roll: 301, Value: 'Color Spray' },
  { Roll: 302, Value: 'Gaze Reflection' },
  { Roll: 303, Value: 'Hypnotism' },
  { Roll: 304, Value: 'Wall of Fog' },
  { Roll: 305, Value: 'Blindness' },
  { Roll: 306, Value: 'Deafness' },
  { Roll: 307, Value: 'Fog Cloud' },
  { Roll: 308, Value: 'Hypnotic Pattern' },
  { Roll: 309, Value: 'Improved Phantasmal Force' },
  { Roll: 310, Value: 'Misdirection' },
  { Roll: 311, Value: 'Continual Darkness' },
  { Roll: 312, Value: 'Illusionary Script' },
  { Roll: 313, Value: 'Non-Detection' },
  { Roll: 314, Value: 'Paralyzation' },
  { Roll: 315, Value: 'Spectral Force' },
  { Roll: 316, Value: 'Dispel Exhaustion' },
  { Roll: 317, Value: 'Emotion' },
  { Roll: 318, Value: 'Improved Invisibility' },
  { Roll: 319, Value: 'Minor Creation' },
  { Roll: 320, Value: 'Phantasmal Killer' },
  { Roll: 321, Value: 'Shadow Monsters' },
  { Roll: 322, Value: 'Chaos' },
  { Roll: 323, Value: 'Demi-Shadow Monsters' },
  { Roll: 324, Value: 'Major Creation' },
  { Roll: 325, Value: 'Projected Image' },
  { Roll: 326, Value: 'Shadow Door' },
  { Roll: 327, Value: 'Shadow Magic' },
  { Roll: 328, Value: 'Summon Shadow' },
  { Roll: 329, Value: 'Demi-Shadow Magic' },
  { Roll: 330, Value: 'Permanent Illusion' },
  { Roll: 331, Value: 'Programmed Illusion' },
  { Roll: 332, Value: 'Shades' },
  { Roll: 333, Value: 'True Sight' },
  { Roll: 334, Value: 'Veil' },
  { Roll: 335, Value: 'Alter Reality' },
  { Roll: 336, Value: 'Prismatic Spray' },
  { Roll: 337, Value: 'Prismatic Wall' },
  { Roll: 338, Value: 'Vision' },
];

// export const SpellsTable = new MyTable(SpellsData, "Spells", '1d338');